# Generated by Django 4.2 on 2023-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='question_pic'),
        ),
    ]
