# Generated by Django 4.2 on 2023-08-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_questions_image_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messages',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_chat', to='app.user_profile'),
        ),
    ]
