# Generated by Django 4.2 on 2023-08-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_chat_messages_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat_Messages',
        ),
    ]
