# Generated by Django 4.2 on 2023-08-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_chat_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to='app.user_profile')),
            ],
        ),
    ]
