# Generated by Django 4.2 on 2023-08-21 18:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_chat_messages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
