# Generated by Django 4.2 on 2023-08-21 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_chat_messages_date_created_contact_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
