# Generated by Django 4.2 on 2023-08-21 18:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messages',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
