# Generated by Django 4.2 on 2023-08-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_chat_messages_message_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Answer',
        ),
    ]
