# Generated by Django 4.2 on 2023-08-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_chatroom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
