# Generated by Django 4.2 on 2023-08-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
