# Generated by Django 4.2 on 2023-08-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_personelchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelchat',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user_profile'),
        ),
    ]
