# Generated by Django 4.2 on 2023-08-29 04:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_personelchat_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='personelchat',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
